### PR TITLE
Developers

### PR DESCRIPTION
**Pull request by isaka-lumato**
- Created API endpoint for the the developers
- Implemented CRUD operations
- We included validations 
## To access the API;
- clone/pull the project
- `-bundle install`
 -  use localhost:3000/api/v1/developers

### CODE REVIEW

**Review by ciraganenicole — CHANGES_REQUESTED** [review]
Hello @Nemwel-Boniface & @isaka-lumato  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Gitflow ✔️ 

## Required Changes ♻️

Max and I have some suggestions:

- Instead of putting an '' email '' column, we suggest that you create an array of social media including contacts 
- We suggest also that you add an "available" column which will be a boolean to show if the developer is available or not
- And finally, the "title" column (eg. Frontend developer)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nemwel-Boniface** [comment]
Hello, @ciraganenicole Thank you for the feedback, We will work on that right now.

**Comment by Nemwel-Boniface** [comment]
## Hello @ciraganenicole and @maxthestranger :wave: 

We have made the following changes:

1. Deleted the email and the tech_stack column in the developer's table
2. Re-added the tech_stack column as a string without an enumerable type
3. Added the title column
4. Added the GitHub, Twitter, and Linkedin columns as separate fields because of problems with validations of enums

**Review by ciraganenicole — APPROVED** [review]

**Review by ciraganenicole — APPROVED** [review]
Hello @Nemwel-Boniface & @isaka-lumato  

Your project is completed, It's time to merge it 🎊  

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Gitflow ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
