### PR TITLE
Book a dev milestone 5 : Documentation

### PR DESCRIPTION
**Pull request by Nemwel-Boniface**
## Hello @maxthestranger  and @ciraganenicole 

-  We auto-created documentation for our API via _**rswag gem**_.

> The documentation explains how to perform all REST requests.

> It also uses rspec to autogenerate test cases that are being used to generate the documentation

### Testing the documentation

- Go to the route localhost:3000/api-docs

image

**Changes on the reservations:**

- [ ] To list all reservations for a specific developer use this route ```http://127.0.0.1:3000/api/v1/users/2/reservations/```

### CODE REVIEW

**Review by ciraganenicole — CHANGES_REQUESTED** [review]
## Hello @Nemwel-Boniface  & @isaka-lumato   :wave: , 

While you made a great effort in this project, unfortunately, there are some changes you need to make

## Status: Required changes ♻️ 

- The documentation is not working properly
api

- And for reservations, I have this error
controller



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Nemwel-Boniface** [comment]
## Hello @ciraganenicole and @maxthestranger :wave: 

We have made the following changes:

- [ ] Fixed the validation issue for the available column
- [ ] Changed the datatype of the phone field to a string
- [ ] Updated the API documentation

**Note:** the errors you might have been facing might be an issue to do with your database. To resolve them follow the following steps in the provided order.

1. Re clone the project in another folder ```git@github.com:maxthestranger/book-a-dev-api.git```
2. Check in the config/database.yml to make sure that the credentials for your local database are correct then proceed 
3. Drop the db ```rails db:drop```
4. Recreate the database again ```rails db:create```
5. Load the schema before migrating the database ```rails db:schema:load```
6. Now migrate the database ```rails db:migrate```
7. Now load the seed data to use it as test data ```rails db:seed```
8. Now ```bundle install``` to install all packages and dependancies
9. Incase the swaggr docs are not updated run ```rake rswag:specs:swaggerize```

**Pictorial visuals of the results of the failing scenarios from the requested changes:**

1. **The reservations for user with id 2**

image

2. **Screenshot for the API docs**

image

**Review by maxthestranger — CHANGES_REQUESTED** [review]
Hi @Nemwel-Boniface and @isaka-lumato , 

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_
_reservations are working well_


## Required Changes ♻️
image

The API documentation is working well, the only caveat is that you need to change the root URL from HTTPS to HTTP according to the error presented in the screenshot above

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by Nemwel-Boniface** [comment]
@maxthestranger I have made the requested changes:

- [ ] Changed the root URL from HTTPS to HTTP
- [ ] Added the includes keyword when fetching reservations to also include the developers
- [ ] Added some test data in the seeds.rb file to test the API

**Comment by maxthestranger** [comment]
Hello @Nemwel-Boniface & @isaka-lumato  

Your project is completed, It's time to merge it 🎊  

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Gitflow ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**Review by maxthestranger — APPROVED** [review]

**Pull request merged**
